version: "2"
services:
  cairo_rest:
    image: rustlang/rust:nightly
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    working_dir: /code
    command: cargo run cairo-rest-server
    volumes:
      - .:/code
